name: movie-app

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:pass@mongodb:27017/moviesApp?authSource=admin
      NODE_ENV: development
      JWT_SECRET: alskdfjlkasdfjlksa23123asdlfk
      PORT: 3000
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
